server:
  # Host IP the server will listen for incoming connections on
  host: "0.0.0.0"

  # Host Port the server will listen for incoming connections on
  port: "8078"

  # Maximum amount of connections to allow to the server
  max_connections: 300

  # Maximum amount of connections to allow from a single IP (0 for unlimited)
  max_connections_per_ip: 3

  # Seconds an IP must wait before reconnecting to the server
  ip_reconnect_limit: 10

  # Number of seconds to wait before dropping an uninitialized connection
  hangup_delay: 10

  # Maximum amount of players allowed to enter the game
  max_players: 200

  # How often to send a ping to connected clients (seconds)
  ping_rate: 60

  # Number of failed login attempts before connection is closed
  max_login_attempts: 3

  # Validate the sequence number sent by the client
  enforce_sequence: true

  # Client version
  min_version: "0.0.28"
  max_version: "0.3.29"

  # How often the server will save all online characters (minutes, 0 to disable)
  save_rate: 5

  # Should the first character created be given admin (level 5) privileges?
  auto_admin: true

database:
  driver: "sqlite"
  host: "127.0.0.1"
  port: "3306"
  name: "goeoserv"
  username: "goeoserv"
  password: "goeoserv"

sln:
  enabled: false
  url: "http://www.apollo-games.com/SLN/sln.php/"
  site: ""
  hostname: ""
  server_name: "Untitled Server"
  rate: 5
  zone: ""

account:
  delay_time: 10
  email_validation: true
  recovery: true
  recovery_show_email: true
  recovery_mask_email: true
  max_characters: 3

smtp:
  from_name: ""
  from_address: ""
  host: ""
  port: 587
  username: ""
  password: ""

new_character:
  spawn_map: 192
  spawn_x: 6
  spawn_y: 6
  spawn_direction: 0  # 0=Down, 1=Left, 2=Up, 3=Right
  home: "Wanderer"

jail:
  map: 76
  x: 6
  y: 7
  free_map: 76
  free_x: 9
  free_y: 11

rescue:
  map: 4
  x: 24
  y: 24
